### ISSUE TITLE
Emilqn

### ISSUE THREAD

**Issue by emilqnn** [thenithinbalaji/Text-Encrypter#11]
- [ ] - _![IMG_20220724_1358478.jpg](https://user-images.githubusercontent.com/51899776/181617073-07822c5a-f526-41f1-babb-9ef7f0641b87.jpg)_

**Comment by thenithinbalaji** [comment]
okay?

**Comment by thenithinbalaji** [comment]
what is this?

**Comment by thenithinbalaji** [comment]
great
